"""DB models

Revision ID: 144b1d9498db
Revises: 
Create Date: 2025-09-20 20:21:07.880608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144b1d9498db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('cod_image', sa.String(length=36), nullable=False),
    sa.Column('cod_ubi', sa.Integer(), nullable=False),
    sa.Column('cod_user', sa.String(length=36), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cod_ubi'], ['ubications.cod_ubi'], ),
    sa.ForeignKeyConstraint(['uploaded_at'], ['dates.cod_date'], ),
    sa.PrimaryKeyConstraint('cod_image')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
