"""remove column

Revision ID: b605eb4ae858
Revises: abfcc3b8db18
Create Date: 2025-09-20 20:22:22.372132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b605eb4ae858'
down_revision: Union[str, Sequence[str], None] = 'abfcc3b8db18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'cod_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('cod_user', mysql.VARCHAR(length=36), nullable=False))
    # ### end Alembic commands ###
